<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 * @var $escaper \Magento\Framework\Escaper
 */
?>

<?php
$object_manager = \Magento\Framework\App\ObjectManager::getInstance();
$customHelper = $object_manager->create('Nxtech\CustomS3Media\Helper\Data');

$_product = $block->getProduct();
$s3Urls = $_product->getData('s3_url');

$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    'https://d2rdfqk6u5busa.cloudfront.net/amazon_main_images/1.webp';


$imageWidth = $block->getImageAttribute('product_page_image_medium', 'width');
$imageHeight = $block->getImageAttribute('product_page_image_medium', 'height');

$galleryJson = $block->getGalleryImagesJson(); // Magento images JSON

$magentoImages = json_decode($galleryJson, true);

$imagesArr = [];
if ($s3Urls) {
    $imagesArr = $customHelper->getCustomImageArray($s3Urls);
}

if ($mainImage) {
    $mergedImages = array_merge($magentoImages, $imagesArr);
} else {
    $mergedImages = $imagesArr;
}

$mergedImagesJson = json_encode($mergedImages);
?>

<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
    <img alt="main product photo" class="gallery-placeholder__image" src="<?= /* @noEscape */ $mainImageData ?>"
        <?= $imageWidth ? 'width="' . $escaper->escapeHtmlAttr($imageWidth) . '"' : '' ?> <?= $imageHeight ? 'height="' . $escaper->escapeHtmlAttr($imageHeight) . '"' : '' ?> />
    <link itemprop="image" href="<?= /* @noEscape */ $mainImageData ?>">
</div>
<?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>
<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @noEscape */ $block->getMagnifier() ?>,
                "data": <?= /* @escapeNotVerified */ $mergedImagesJson ?>,
                "options": <?= /* @noEscape */ $block->getGalleryOptions()->getOptionsJson() ?>,
                "fullscreen": <?= /* @noEscape */ $block->getGalleryOptions()->getFSOptionsJson() ?>,
                 "breakpoints": <?= /* @noEscape */ $block->getBreakpoints() ?>
            }
        }
    }
</script>